apiVersion: v1
kind: Pod
metadata:
  name: green-color-api
  labels:
    app: green-color-api
spec:
  containers:
  - name: color-api
    image: fabiancienfuegosc/color-api:1.3.0
    envFrom:
      - configMapRef:
          name: green-env-vars
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits: 
        memory: "256Mi"
        cpu: "600m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: color-config
        mountPath: /mnt/config
        readOnly: true
  volumes:
    - name: color-config
      configMap:
        name: green-files