apiVersion: v1
kind: Pod
metadata:
  name: nginx-priviliged
  labels:
    name: nginx-priviliged
spec:
  containers:
    - name: nginx
      image: nginx:1.27.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
