apiVersion: v1
kind: Pod
metadata:
  name: red-color-api
  labels:
    app: red-color-api
spec:
  containers:
  - name: color-api
    image: fabiancienfuegosc/color-api:1.3.0
    ### Way to handle multiple EnvVars
    # envFrom:
    #   - configMapRef:
    #       name: red-config
    ### This way is for specific ENV 
    env:
      - name: DEFAULT_COLOR
        valueFrom:
          configMapKeyRef:
            key: COLOR
            name: red-config
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80