apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-ss
spec:
  serviceName: busybox
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:1.36.1
          command:
            - "sh"
            - "-c"
            - "sleep 3600"
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: local-volume
              mountPath: /mnt/local
  ## To create automatically Claims
  volumeClaimTemplates:
    - metadata:
        name: local-volume
      spec:
        accessModes:
          - ReadWriteOnce
        # for static PV
        # storageClassName: local-storage
        # for dynamic PV
        storageClassName: standard
        resources:
          requests:
            storage: 128Mi