apiVersion: v1
kind: Pod
metadata:
  name: traffic-gen
  labels:
    app: traffic-gen
spec:
  containers:
    - name: traffic-gen
      image: fabiancienfuegosc/traffic-gen:1.0.0 
      args:
      ## servicename.namespace.svc.cluster.local
        - "color-api-svc.dev.svc.cluster.local/api"
        - "1"