apiVersion: v1
kind: Pod
metadata:
  name: color-api
  labels:
    app: color-api
spec:
  containers:
    - name: color-api
      image: fabiancienfuegosc/color-api:1.2.1
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "400m"
          memory: "512Mi"
        limits:
          cpu: "800m"
          memory: "1Gi"
      env:
        - name: DELAY_STARTUP
          value: "false"
        - name: DELAY_LIVENESS
          value: "true"
      startupProbe:
        httpGet:
          path: /up
          port: 80
        failureThreshold: 2
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /health
          port: 80
        failureThreshold: 3
        periodSeconds: 10