apiVersion: v1
kind: Pod
metadata:
  name: traffic-gen
  labels:
    app: traffic-gen
spec:
  containers:
    - name: traffic-gen
      image: fabiancienfuegosc/traffic-gen:1.0.0
      resources:
        requests:
          cpu: "400m"
          memory: "512Mi"
        limits:
          cpu: "800m"
          memory: "1Gi"
      args:
        - "color-api-svc/api"
        - "0.5"