apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api-deploy
  labels:
    app: color-api
spec:
  selector:
    matchLabels:
      app: color-api
      enviroment: local
      tier: backend
    matchExpressions:
      - key: managed
        operator: Exists
  replicas: 3
  template:
    metadata:
      labels:
        app: color-api
        enviroment: local
        tier: backend
        managed: "deployment"
    spec:
      containers:
        - name: color-api
          image: fabiancienfuegosc/color-api:1.1.0
          ports:
            - containerPort: 80
