apiVersion: v1
kind: Pod
metadata:
  name: color-api-backend
  labels:
    app: color-api
    enviroment: local
    tier: backend
spec:
  containers:
  - name: color-api-backend
    image: fabiancienfuegosc/color-api:1.1.0
    ports:
    - containerPort:  80

---

apiVersion: v1
kind: Pod
metadata:
  name: color-api-frontend
  labels:
    app: color-api
    enviroment: local
    tier: frontend
spec:
  containers:
  - name: color-api-frontend
    image: nginx:1.27.0
    ports:
    - containerPort:  80